name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for changelog generation

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies �
        run: npm ci

      - name: Generate changelog 📝
        run: npm run build-changelog

      - name: Build application 🔧
        env:
          VITE_UMAMI_URL: ${{ vars.VITE_UMAMI_URL }}
          VITE_UMAMI_WEBSITE_ID: ${{ vars.VITE_UMAMI_WEBSITE_ID }}
        run: npm run build

      - name: Move changelog to dist 📋
        run: cp changelog.json dist/spa/changelog.json

      - name: Add .nojekyll file
        run: touch dist/spa/.nojekyll

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa
          publish_branch: deploy-branch
          keep_files: false
